/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: butterflybliss (https://sketchfab.com/ZorDob)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bumblebee-553e8e1f73354f5c911825d011cd3e49
Title: Bumblebee
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import scene from '/models/bumblebee/bee_scene.gltf'


const BeeContact = ({ currentAnimation, ...props }) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (!actions || !currentAnimation) return;

    const action = actions[currentAnimation];
    if (action) {
        action.reset().fadeIn(0.05).play();
        action.timeScale = 0.5; // Adjust speed if needed
        return () => action.fadeOut(0.05);
    }
    }, [actions, currentAnimation]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.997}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_0" rotation={[-Math.PI / 2, 0, 0]} scale={1.002}>
                <group name="root_1">
                  <group name="GLTF_SceneRootNode_2" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Sketchfab_model_0_3" rotation={[-Math.PI / 2, 0, 0]} scale={0.004}>
                      <group name="root_1_4">
                        <group name="GLTF_SceneRootNode_2_5" rotation={[Math.PI / 2, 0, 0]}>
                          <group name="GLTF_created_0_3_6">
                            <group name="GLTF_created_0_7">
                              <group name="GLTF_created_0">
                                <primitive object={nodes.GLTF_created_0_rootJoint} />
                                <skinnedMesh
                                  name="Object_83"
                                  geometry={nodes.Object_83.geometry}
                                  material={materials.material0000}
                                  skeleton={nodes.Object_83.skeleton}
                                />
                                <skinnedMesh
                                  name="Object_86"
                                  geometry={nodes.Object_86.geometry}
                                  material={materials.material0001}
                                  skeleton={nodes.Object_86.skeleton}
                                />
                                <group name="Object_78_78_correction">
                                  <group name="Object_78_78" />
                                </group>
                                <group name="Object_81_81_correction">
                                  <group name="Object_81_81" />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default BeeContact
