import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Conrad Justin (https://sketchfab.com/ConradJustin)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/baker-and-the-bridge-da3f6e7b85ed44b7aa8bb5571e365abc
Title: Baker and the Bridge
*/

import islandScene from '../baker_and_the_bridge/scene.gltf';

const Island = (props) => {
    const islandRef = useRef()

    const { nodes, materials } = useGLTF(islandScene)
    return (
        <a.group ref={islandRef} {...props}>
        <group rotation={[Math.PI / 2, 0, -Math.PI]}>
            <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
            <group rotation={[0, 0, -Math.PI / 2]} scale={100}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.characters_STONE_a_0.geometry}
                material={materials.STONE_a}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.characters_STONE_a_0_1.geometry}
                material={materials.STONE_a}
            />
          </group>
          <group rotation={[0, 0, -Math.PI / 2]} scale={100}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.characters007_bush_0.geometry}
                material={materials.bush}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.characters007_bush_0_1.geometry}
                material={materials.bush}
            />
          </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.characters001_charcters_0.geometry}
                material={materials.charcters}
                rotation={[0, 0, -Math.PI / 2]}
                scale={100}
          />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.characters002_watermill_0.geometry}
                material={materials.watermill}
                rotation={[0, 0, -Math.PI / 2]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.characters003_terrain_left_0.geometry}
                material={materials.terrain_left}
                rotation={[0, 0, -Math.PI / 2]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.characters004_house_0.geometry}
                material={materials.house}
                rotation={[0, 0, -Math.PI / 2]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.characters005_bridge_0.geometry}
                material={materials.bridge}
                rotation={[0, 0, -Math.PI / 2]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.characters006_tree_0.geometry}
                material={materials.tree}
                rotation={[0, 0, -Math.PI / 2]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.characters008_water_0.geometry}
                material={materials.water}
                rotation={[0, 0, -Math.PI / 2]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.characters009_terrain_right_0.geometry}
                material={materials.terrain_right}
                rotation={[0, 0, -Math.PI / 2]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.characters010_wheat_0.geometry}
                material={materials.wheat}
                rotation={[0, 0, -Math.PI / 2]}
                scale={100}
            />
            </group>
        </group>
    </a.group>
  )
}

export default Island
